### ISSUE TITLE
missing <!DOCTYPE html>

### ISSUE THREAD

**Issue by mbrochh** [koba04/react-boilerplate#10]
I'm not sure if this really is an issue, but most other react boilerplates that I have seen go to great lengths to somehow include `<!DOCTYPE html>` when the server returns the page.

Some boilerplates use a templating engine because of this, your boilerplate renders the base template in `App.js`, in that case, most boilerplates do this:

```
app.use((req, res) => {
  Router.run(routes, req.path, (Handler) => {
    res.send(
      '<!DOCTYPE html>' + React.renderToString(<Handler path={req.path} />));
  });
});
```

Do you think this should be in included in this boilerplate? Any reason why it has been left out so far?

**Comment by koba04** [comment]
Nope, I've added it!
Thank you!
