### ISSUE TITLE
Integrate with flux?

### ISSUE THREAD

**Issue by AllenFang** [koba04/react-boilerplate#20]
This is a cool stuff for Isomorphic react demo. It's very useful. However, would you have any plan or idea for integrating flux in this demo? It will be great:)

**Comment by koba04** [comment]
@AllenFang 
Thank you for your interest!

> However, would you have any plan or idea for integrating flux in this demo?

What do you mean?
I think this sample is implemented with flux architecture.

https://github.com/koba04/react-boilerplate/tree/master/app

**Comment by AllenFang** [comment]
@koba04 , sorry..  i'm compare your example with another, but leave issues in wrong place! Anyway your example is great :)

**Comment by koba04** [comment]
Thanks!
