### ISSUE TITLE
Add /dist to .gitignore

### ISSUE THREAD

**Issue by helpermethod** [koba04/react-boilerplate#7]
The `dist` folder shouldn't be included in the git repository as it can be reconstructed from the source.

**Comment by koba04** [comment]
Indeed, but this is because I want to deploy a application on Heroku only `git push`.

**Comment by koba04** [comment]
I've known it is possible by using `npm postinstall`.
https://github.com/koba04/react-boilerplate/commit/811a844a47da0de04fd7af53c112c6a4c64ff051

Thank you! :smile:
