### ISSUE TITLE
Failed test

### ISSUE THREAD

**Issue by koba04** [koba04/react-boilerplate#9]
```
> jest

Waiting on 1 test...zsh: segmentation fault  npm run test
```

**Comment by mbrochh** [comment]
I'm getting the same on OSX. If I remember correctly, I had the same on another boilerplate that I tried. It seems to be an issue with node.js - I think someone mentioned that it works with io.js

I haven't had the time to verify that claim, though.

**Comment by koba04** [comment]
@mbrochh 
Yes, the mentioned issue is probably this.
https://github.com/facebook/jest/issues/243#issuecomment-91383062

I tried testing with io.js, the result is below.
https://travis-ci.org/koba04/react-boilerplate/jobs/58241315

The test is failed but error isn't segmentation fault. It may be fixed with io.js.

**Comment by phungnc** [comment]
@koba04 
Follow this comment, I switch to node v0.10 and It work fine.
https://github.com/facebook/jest/issues/243#issuecomment-88285265

Result is:
```
Using Jest CLI v0.4.0
 PASS  app/components/__tests__/InputArtistTest.js (1.133s)
1 test passed (1 total)
Run time: 1.343s
```

**Comment by koba04** [comment]
yes, I'm using node v0.10 for passing the test.
https://github.com/koba04/react-boilerplate/blob/master/.travis.yml#L3

facebook uses jest on node v0.10 too.
https://github.com/facebook/react/blob/master/.travis.yml#L4

But, I'd like to use latest node version... (v0.12.5)

I close this issue once.
I'll reconsider unit test environment at #18.
